version: '3.7'
services:
  node1:
    container_name: node1
    image: bitcoinsv/bitcoin-sv:1.0.8.beta
    ports:
      - "18332:18332"
      - "18333:18333"
      - "28332:28332"
    volumes:
      - ./config/bitcoin.conf:/data/bitcoin.conf
      - node1-data:/data

  node2:
    container_name: node2
    image: bitcoinsv/bitcoin-sv:1.0.8.beta
    ports:
      - "18501:18333"
      - "18502:18332"
    volumes:
      - ./config/bitcoin.conf:/data/bitcoin.conf
      - node2-data:/data

  node3:
    container_name: node3
    image: bitcoinsv/bitcoin-sv:1.0.8.beta
    ports:
      - "18601:18333"
      - "18602:18332"
    volumes:
      - ./config/bitcoin.conf:/data/bitcoin.conf
      - node3-data:/data

volumes:
  node1-data:
  node2-data:
  node3-data:
